services:
   frontend:
      container_name: my-react-app
      build:
         context: ./charging-app
         target: development
      volumes:
         - ./charging-app:/app
         - /app/node_modules
      ports:
         - 3000:3000
      command: npm run dev